type: local
# (true/false) Enable local storage to use it via the Backuper
enabled: true
# (true/false) With automatic backup, backups will be saved to specified local storage. Works only if 'enabled: true'
autoBackup: true

# (Path) Full directory where backups will be stored
backupsFolder: ./plugins/Backuper/Backups

# (>= 0) Max backups in backups folder, 0 to make it unlimited
maxBackupsNumber: 0
# (MB >= 0) Max backups folder weight, 0 to make it unlimited
maxBackupsWeight: 0

# (true/false) Should backups be packaged in a zip archive
zipArchive: true
# (0 - 9) archive compression level. A higher value may reduce file size but may also increase the time required to archive and decompress
zipCompressionLevel: 5