type: sftp
# (true/false) Enable SFTP storage to use it via the Backuper
enabled: false
# (true/false) With automatic backup, backups will be saved to a specified SFTP server. Works only if 'enabled: true'
autoBackup: true

# (Path) SFTP server directory where backups will be stored
backupsFolder: ./
# (Symbol) Path separator symbol used on SFTP SERVER. For example, '/' on UNIX systems and '\' on windows
pathSeparatorSymbol: /

# (>= 0) Max backups in backups folder, 0 to make it unlimited
maxBackupsNumber: 0
# (MB >= 0) Max backups folder weight, 0 to make it unlimited
maxBackupsWeight: 0

# (true/false) Should backups be packaged in a zip archive
zipArchive: true
# (0 - 9) archive compression level. A higher value may reduce file size but may also increase the time required to archive and decompress
zipCompressionLevel: 5

auth:
  # (Address) SFTP server address
  address: ''
  # (Port) SFTP server port
  port: 22
  # (password/key) SFTP server authentication type
  authType: password
  # (Username) SFTP server username to use for authentication
  username: ''
  # (Password) SFTP server password to use for authentication
  password: ''
  # (Absolute Path) Local path to key file if 'authType: key'
  keyFilePath: ''
  # (true/false) Do you want to specify local knownHostsFile?
  useKnownHostsFile: false
  # (Path) Path to local knownHostsFile if 'useKnownHostsFile: true'
  knownHostsFilePath: ''
  # (Path)
  sshConfigFilePath: ''